site_name: AIandOS
site_author: javierlj04
site_description: AI and Open Science Documentation

theme:
  name: material
  language: es

nav:
  - Home: index.md

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - toc